# Generated by Django 2.0.4 on 2018-06-05 09:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generic_model', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericmodel',
            name='data',
        ),
        migrations.AddField(
            model_name='genericmodel',
            name='_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
